databases:
  - name: dispatchgo-postgres
    plan: free
    databaseName: dispatchgo
    user: dispatch_user
    ipAllowList: []

services:
  - type: pserv
    name: dispatchgo-rabbitmq
    image: rabbitmq:3-management
    disk:
      name: rabbitmq-data
      mountPath: /var/lib/rabbitmq
      sizeGB: 5
    envVars:
      - key: RABBITMQ_DEFAULT_USER
        value: dispatchgo_user
      - key: RABBITMQ_DEFAULT_PASS
        value: YourStrongPass123!@#
      - key: RABBITMQ_ERLANG_COOKIE
        value: SuperSecretCookie2026XYZ

  - type: web
    name: dispatchgo-api
    runtime: docker
    plan: free
    dockerContext: ./api-service
    dockerfilePath: ./api-service/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: APP_PORT
        value: "8080"
      - key: HMAC_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: dispatchgo-postgres
          property: connectionString
      - key: RABBITMQ_URL
        fromService:
          name: dispatchgo-rabbitmq
          property: connectionString
      - key: RABBITMQ_EXCHANGE
        value: webhooks
      - key: RABBITMQ_QUEUE
        value: webhook.jobs
      - key: RABBITMQ_ROUTING_KEY
        value: webhook.jobs